FROM node:16-alpine 

WORKDIR /app

COPY . .

#After "RUN" you can write your env varieble or other command. It works like a regular bash command line
#RUN <your command>
ARG REACT_APP_LOGIK_API=${REACT_APP_LOGIK_API}
ARG REACT_APP_LOGIK_PRODUCT_ID=${REACT_APP_LOGIK_PRODUCT_ID} 
ARG REACT_APP_LOGIK_TOKEN=${REACT_APP_LOGIK_TOKEN} 
ARG REACT_APP_USER_NAME=${REACT_APP_USER_NAME} 
ARG REACT_APP_PASSWORD=${REACT_APP_PASSWORD} 

ENV REACT_APP_LOGIK_API=$REACT_APP_LOGIK_API \
    REACT_APP_LOGIK_PRODUCT_ID=$REACT_APP_LOGIK_PRODUCT_ID \
    REACT_APP_LOGIK_TOKEN=$REACT_APP_LOGIK_TOKEN \
    REACT_APP_USER_NAME=$REACT_APP_USER_NAME \
    REACT_APP_PASSWORD=$REACT_APP_PASSWORD

RUN npm install
RUN npm run build

CMD ["node", "server.js"]
